# Change these first
owner: complexdatacollective # Your GitHub organization or username, where this repository lives
repo: service-status # The name of this repository

sites:
  - name: Project homepage
    url: https://networkcanvas.com
  - name: Documentation site
    url: https://documentation.networkcanvas.com
  - name: Partner services
    url: https://partnerservices.networkcanvas.com

status-website:
  # cname: demo.upptime.js.org
  baseUrl: /service-status
  logoUrl: https://raw.githubusercontent.com/complexdatacollective/service-status/master/assets/NC-Mark.svg
  name: Network Canvas Project
  introTitle: "Welcome to the service status page for the Network Canvas project."
  introMessage: Please find automated service status data for all our project services below, along with up to date incident information. If a service is down or not working correctly, and there is no incidicent below, please [contact us](mailto:info@networkcanvas.com).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
